language: go

go:
    - "1.11"
    - "1.12"
    - "1.13"
    - "1.14"
    - "1.15"

env:
  - GO111MODULE=on

before_script:
    - curl -O http://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf

script:
    - TESTFILE=bremen-latest.osm.pbf go test -v -race
